answers/urls.py
from django.urls import path
from . import views

app_name = 'answers'

urlpatterns = [
    path('', views.AnswerCreateView.as_view(), name='answer'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('questions.urls')),
    path('users/', include('users.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path, include
from . import views


app_name = 'questions'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('questions/create/', views.CreateView.as_view(), name='create'),
    path('questions/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('questions/<int:pk>/answers/', include('answers.urls')),
    path('questions/<int:pk>/delete', views.DeleteView.as_view(), name='delete'),
]

users/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = "users"
urlpatterns = [
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in/', LoginView.as_view(template_name='users/sign_in.html'), name='sign_in'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('<int:pk>/', views.UserPageView.as_view(), name='mypage'),
]

answers/models.py
from django.db import models

class Answer(models.Model):
    class Meta:
      db_table = 'answers'

    question = models.ForeignKey('questions.Question', on_delete=models.CASCADE)  
    content = models.TextField()
    name = models.CharField()

questions/models.py
from django.db import models
from django.conf import settings


class Question(models.Model):
  class Meta:
    db_table = 'questions'

  title = models.CharField(null=False)
  content = models.TextField(null=False)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# カスタム ユーザーマネージャー
class CustomUserManager(BaseUserManager):
    def create_user(self, email, nickname, password=None, **extra_fields):
        if not email:
            raise ValueError('Email address is required')
        email = self.normalize_email(email)
        user = self.model(email=email, nickname=nickname, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
# カスタム ユーザーモデル
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    nickname = models.CharField(max_length=50, null=False)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']

    objects = CustomUserManager()

    def __str__(self):
        return self.email

answers/forms.py
from django import forms
from .models import Answer

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['name','content']

        widgets = {
            'content': forms.Textarea(attrs={'placeholder': '回答する', 'rows': 3}),
            'name': forms.TextInput(attrs={'placeholder': '投稿者名', 'rows': 1}),
        }

questions/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content']

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'タイトル', 'rows': 1}),
            'content': forms.Textarea(attrs={'placeholder': '質問内容', 'rows': 3}),
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()  # カスタムユーザーモデルを取得
        fields = ('email', 'nickname',)  # 'email' と 'nickname' を追加

answers/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import AnswerForm

class AnswerCreateView(View):
  def post(self, request, *args, **kwargs):
    form = AnswerForm(request.POST)
    if form.is_valid():
      answer = form.save(commit=False)
      answer.question_id = kwargs['pk']
      answer.save()
      return redirect('questions:detail', pk=answer.question_id)
    else:
      return render(request, 'questions:detail', {'form': form, 'pk': answer.question_id})

questions/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView,DetailView,DeleteView
from .models import Question
from .forms import QuestionForm
from django.views.generic.edit import FormMixin ,DeleteView
from answers.forms import AnswerForm
from answers.models import Answer
from django.db.models import Count

class IndexView(ListView):
    model = Question
    template_name = 'questions/index.html'
    context_object_name = 'questions'

    def get_queryset(self):
        return Question.objects.annotate(num_answers=Count('answer'))

class CreateView(CreateView):
    template_name = 'questions/create.html'
    form_class = QuestionForm
    success_url = reverse_lazy('questions:index')

    def form_valid(self, form):
      question = form.save(commit=False)
      question.user = self.request.user
      question.save()
      return super().form_valid(form)

class DetailView(DetailView, FormMixin):
    model = Question
    template_name = 'questions/detail.html'
    form_class = AnswerForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answers = Answer.objects.filter(question=self.object)
        context['answers'] = answers
        context['form'] = self.get_form()
        return context
    
class DeleteView(DeleteView):
    model = Question
    success_url = reverse_lazy('questions:index')

users/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm
from django.views.generic import ListView
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from questions.models import Question
User = get_user_model()

class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('questions:index')  # 登録完了後にリダイレクトするURL
    template_name = 'users/sign_up.html'

class UserPageView(ListView):
    model = Question
    template_name = 'users/mypage.html'  # テンプレート名を適切に設定
    context_object_name = 'question'  # テンプレートに渡すコンテキスト変数名

    def get_queryset(self):
        # URLからユーザーIDを取得（'user_id'はurls.pyで設定したパラメータ名に合わせてください）
        user_id = self.kwargs.get('pk')
        # そのIDに対応するユーザーを取得（存在しなければ404エラー）
        self.user = get_object_or_404(User, pk=user_id)
        # そのユーザーに関連するツイートを取得
        return Question.objects.filter(user=self.user)

    def get_context_data(self, **kwargs):
        # ビューに渡す追加のコンテキスト変数を定義
        context = super().get_context_data(**kwargs)
        context['profile_user'] = self.user  # プロフィールページの所有者
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>TechChat</title>
    <link rel="stylesheet" href="{% static 'css/questions.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
  </head>

  <body> 
    <header>
      <div class='header-contents'>
        <div class='logo'>
          <a href="{% url 'questions:index' %}">TechChat</a>
        </div>
          {% if user.is_authenticated %}
          <div class='login-button'>
          <div class='post-button'><a href="{% url 'questions:create' %}">質問する</a></div>
          <div class='post-button'><a href="{% url 'logout' %}">ログアウト</a></div>
          </div>
          {% else %}
          <div class="grid-6">
            <div class="post-button"><a href={% url "users:sign_in" %}>ログイン</a></div>
            <div class="post-button"><a href={% url "users:sign_up" %}>新規登録</a></div>
          </div>
          {% endif %}
        </div>
      </div>
    </header>

    {% block content %}{% endblock content %}


  </body>
</html>

templates/questions/create.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class='new-main'>
  <!-- フォーム -->
  <div class='form'>
    <!-- フォームのヘッダー表示 -->
    <div class='form-top'>
    </div>

    <!-- フォームのメイン部分 -->
    <div class='form-main'>
      <form method="post">
      {% csrf_token %}
      <div class='input-items'>
        <div class='input-items__title'>
          {{ form.title }}
        </div>
        <div class='input-items__content'>
          {{ form.content }}
        </div>
        <button type="submit" class="input-items__submit">POST</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

templates/questions/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="show-main">
  <div class="show-contents">
    <!-- 質問内容の表示 -->
    <div class="show-question">
      <div class="show-question__title">
        {{ question.title}}
      </div>
      <div class="show-question__content">
        {{ question.content}}
      </div>
      <div class="show-question__name">
        {{ question.user.nickname}}
      </div>
      {% if question.user == request.user %}
      <div class="delete">
        <form action="{% url 'questions:delete' question.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="削除" class="delete-btn">
        </form>
      </div>
      {% endif %}
    </div>

    <!-- 回答投稿フォームの表示 -->
    <div class="show-answer-form">
      <form method="post" action="{% url 'questions:answers:answer' pk=question.id %}">
        {% csrf_token %}
        <div class="show-answer-form__heading">
          回答する
        </div>
        <div class="show-answer-form__content">
          {{ form.content }}
        </div>
        <div class="show-answer-form__name">
           {{ form.name }}
        </div>
        <div class="show-answer-form__submit">
          <input type="submit" value="POST">
        </div>
      </form>
    </div>

    <!-- 回答一覧の表示 -->
    <div class="show-answers">
      <div class="answers-heading">
        いままでの回答：
      </div>
      {% for answer in answers %}
        <div class="answer-content">
          <div class="answer-content__text">
            {{ answer.content }}
          </div>
          <div class="answer-content__name">
            {{ answer.name }}
          </div>
        </div>
      {% endfor %}
    </div>  
  </div>  
</div>  

{% endblock content %}

templates/questions/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- 一覧表示画面 -->
<div class='index-main'>
  <div class='post-contents'>
    {% for question in questions %}
    <!-- 投稿１件分の表示 -->
      <div class='post-content'>
        <!-- コメントに関する表示 -->
        <div class='comment'>
          <div class='comment__num'>
            {{ question.num_answers }}
          </div>
          <div class='comment__unit'>
            comments
          </div>
        </div>

        <!-- 質問本文の表示 -->
        <div class='question'>
          <div class='question-top'>
            <div class='question-top__title'>
              <a href="{% url 'questions:detail' question.pk %}">{{ question.title }}</a>
            </div>
            <div class='question-top__name'>
              {{ question.user.nickname}}
            </div>
          </div>
          <div class='question-bottom'>
            <div class='question-bottom__content'>
              {{ question.content}}
            </div>
          </div>
        {% if question.user == request.user %}
        <div class="delete">
          <form action="{% url 'questions:delete' question.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="削除" class="delete-btn">
          </form>
        </div>
        {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

templates/users/mypage.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="contents row">
  {% include 'tweets/index.html' %}
</div>

{% endblock content %}

templates/users/sign_in.html
{% extends "base.html" %}
{% block content %}

<form method="post">
  {% csrf_token %}

    <div class="contents row">
        <div class="container">
            <h2>Log in</h2>
            <div class="field">
                {{ form.username.label_tag }}
                {{ form.username }}
                {% if form.username.errors %}
                <ul class="errorlist">
                    {% for error in form.username.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.password.label_tag  }}<a>(英数字含む8文字以上)</a>
                {{ form.password }}
                {% if form.password.errors %}
                <ul class="errorlist">
                    {% for error in form.password.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="actions">
                <input type="submit" value="Log in">
            </div>
        </div>
    </div>

</form>
{% endblock content %}

templates/users/sign_up.html
{% extends "base.html" %}
{% block content %}

<form method="post">
  {% csrf_token %}

    <div class="contents row">
        <div class="container">
            <h2>Sign up</h2>
            {% if form.errors %}
            <div class="error">
                <p>入力にエラーがあります。もう一度ご確認ください。</p>
                {{ form.non_field_errors }}
            </div>
        {% endif %}
            <div class="field">
                {{ form.nickname.label_tag }}
                {{ form.nickname }}
                {% if form.nickname.errors %}
                <ul class="errorlist">
                    {% for error in form.nickname.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.email.label_tag  }}
                {{ form.email }}
                {% if form.email.errors %}
                <ul class="errorlist">
                    {% for error in form.email.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.password1.label_tag  }}<a>(英数字含む8文字以上)</a>
                {{ form.password1 }}
                {% if form.password1.errors %}
                <ul class="errorlist">
                    {% for error in form.password1.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.password2.label_tag  }}
                {{ form.password2 }}
                {% if form.password2.errors %}
                <ul class="errorlist">
                    {% for error in form.password2.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="actions">
                <input type="submit" value="Sign Up">
            </div>
        </div>
    </div>

</form>
{% endblock content %}